// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrIgor.Infrastructure.Data;

#nullable disable

namespace MrIgor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MrIgor.Core.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex1")
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex1")
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MrIgor.Core.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AssessmentId")
                        .HasName("PK__Assessme__3D2BF81EDD65C589");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.ToTable("Assessments", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime?>("AttendedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69261C363C9B7A");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.ToTable("Attendance", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassroomId"));

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassroomId")
                        .HasName("PK__Classroo__11618EAAEA32DC3B");

                    b.HasIndex("TenantId");

                    b.ToTable("Classrooms", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ExamId")
                        .HasName("PK__Exams__297521C7A36B965C");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.ToTable("Exams", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12FE7BBADC");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.ToTable("Notifications", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__9C8A5B49821B2F9C");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.ToTable("Schedules", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("Score1")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Score");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScoreId")
                        .HasName("PK__Scores__7DD229D18032CA2C");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.ToTable("Scores", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId")
                        .HasName("PK__Sessions__C9F492902F42498B");

                    b.HasIndex("TenantId");

                    b.ToTable("Sessions", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.StudentSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__StudentS__3214EC072CD4AF8B");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "StudentId", "SubjectId" }, "UQ_Student_Subject")
                        .IsUnique();

                    b.ToTable("StudentSubjects", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.StudentSubjectApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__StudentS__3214EC071B055513");

                    b.HasIndex("StudentSubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TenantId");

                    b.ToTable("StudentSubjectApprovals", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA3A80BC4A452");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TenantId");

                    b.ToTable("Subjects", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.TeachersSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Teachers__3214EC07B62212B0");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "TeacherId", "SubjectId" }, "UQ_Teacher_Subject")
                        .IsUnique();

                    b.ToTable("TeachersSubjects", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PaymentURL");

                    b.Property<string>("SchoolType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubcriptionPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TenantId")
                        .HasName("PK__Tenants__2E9B47E170819AFD");

                    b.ToTable("Tenants", "Academic");
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetRole", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("AspNetRoles")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_AspNetRoles_Tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("MrIgor.Core.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUser", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("AspNetUsers")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_AspNetUsers_Tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("MrIgor.Core.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("MrIgor.Core.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUserRole", b =>
                {
                    b.HasOne("MrIgor.Core.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_AspNetUserRoles_Tenant");

                    b.HasOne("MrIgor.Core.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUserToken", b =>
                {
                    b.HasOne("MrIgor.Core.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MrIgor.Core.Models.Assessment", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Subject", "Subject")
                        .WithMany("Assessments")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Assessments_Subject");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Assessments")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Assessments_Tenant");

                    b.Navigation("Subject");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Attendance", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Classroom", "Classroom")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassroomId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Classroom");

                    b.HasOne("MrIgor.Core.Models.AspNetUser", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Student");

                    b.HasOne("MrIgor.Core.Models.Subject", "Subject")
                        .WithMany("Attendances")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Subject");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Attendances")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Tenant");

                    b.Navigation("Classroom");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Classroom", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Classrooms")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Classrooms_Tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Exam", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Subject");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Exams")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Exams_Tenant");

                    b.Navigation("Subject");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Notification", b =>
                {
                    b.HasOne("MrIgor.Core.Models.AspNetUser", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Recipient");

                    b.HasOne("MrIgor.Core.Models.Subject", "Subject")
                        .WithMany("Notifications")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Notifications_Subject");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Notifications")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Tenant");

                    b.Navigation("Recipient");

                    b.Navigation("Subject");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Schedule", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Classroom", "Classroom")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassroomId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Classroom");

                    b.HasOne("MrIgor.Core.Models.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Subject");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Schedules")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Tenant");

                    b.Navigation("Classroom");

                    b.Navigation("Subject");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Score", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Assessment", "Assessment")
                        .WithMany("Scores")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("FK_Scores_Assessment");

                    b.HasOne("MrIgor.Core.Models.Exam", "Exam")
                        .WithMany("Scores")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK_Scores_Exam");

                    b.HasOne("MrIgor.Core.Models.AspNetUser", "Student")
                        .WithMany("Scores")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Scores_Student");

                    b.HasOne("MrIgor.Core.Models.Subject", "Subject")
                        .WithMany("Scores")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Scores_Subject");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Scores")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Scores_Tenant");

                    b.Navigation("Assessment");

                    b.Navigation("Exam");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Session", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Sessions")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Sessions_Tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.StudentSubject", b =>
                {
                    b.HasOne("MrIgor.Core.Models.AspNetUser", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentSubjects_Student");

                    b.HasOne("MrIgor.Core.Models.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentSubjects_Subject");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentSubjects_Tenant");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.StudentSubjectApproval", b =>
                {
                    b.HasOne("MrIgor.Core.Models.StudentSubject", "StudentSubject")
                        .WithMany("StudentSubjectApprovals")
                        .HasForeignKey("StudentSubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Approvals_StudentSubject");

                    b.HasOne("MrIgor.Core.Models.AspNetUser", "Teacher")
                        .WithMany("StudentSubjectApprovals")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Approvals_Teacher");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("StudentSubjectApprovals")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Approvals_Tenant");

                    b.Navigation("StudentSubject");

                    b.Navigation("Teacher");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Subject", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Classroom", "Classroom")
                        .WithMany("Subjects")
                        .HasForeignKey("ClassroomId")
                        .HasConstraintName("FK_Subjects_Classroom");

                    b.HasOne("MrIgor.Core.Models.Session", "Session")
                        .WithMany("Subjects")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_Subjects_Session");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("Subjects")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Subjects_Tenant");

                    b.Navigation("Classroom");

                    b.Navigation("Session");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.TeachersSubject", b =>
                {
                    b.HasOne("MrIgor.Core.Models.Subject", "Subject")
                        .WithMany("TeachersSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_TeachersSubjects_Subject");

                    b.HasOne("MrIgor.Core.Models.AspNetUser", "Teacher")
                        .WithMany("TeachersSubjects")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_TeachersSubjects_Teacher");

                    b.HasOne("MrIgor.Core.Models.Tenant", "Tenant")
                        .WithMany("TeachersSubjects")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_TeachersSubjects_Tenant");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MrIgor.Core.Models.AspNetUser", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Notifications");

                    b.Navigation("Scores");

                    b.Navigation("StudentSubjectApprovals");

                    b.Navigation("StudentSubjects");

                    b.Navigation("TeachersSubjects");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Assessment", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Classroom", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Schedules");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Exam", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Session", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("MrIgor.Core.Models.StudentSubject", b =>
                {
                    b.Navigation("StudentSubjectApprovals");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Subject", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Attendances");

                    b.Navigation("Exams");

                    b.Navigation("Notifications");

                    b.Navigation("Schedules");

                    b.Navigation("Scores");

                    b.Navigation("StudentSubjects");

                    b.Navigation("TeachersSubjects");
                });

            modelBuilder.Entity("MrIgor.Core.Models.Tenant", b =>
                {
                    b.Navigation("AspNetRoles");

                    b.Navigation("AspNetUserRoles");

                    b.Navigation("AspNetUsers");

                    b.Navigation("Assessments");

                    b.Navigation("Attendances");

                    b.Navigation("Classrooms");

                    b.Navigation("Exams");

                    b.Navigation("Notifications");

                    b.Navigation("Schedules");

                    b.Navigation("Scores");

                    b.Navigation("Sessions");

                    b.Navigation("StudentSubjectApprovals");

                    b.Navigation("StudentSubjects");

                    b.Navigation("Subjects");

                    b.Navigation("TeachersSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
